services:
  beesd:
    container_name: beesd
    privileged: true
    restart: unless-stopped
    hostname: beesd
    build:
      context: .
    image: rylos/beesd:latest
    environment:
      - TZ=Europe/Rome
      - HASH_TABLE=/mnt/.beeshome/beeshash.dat
      - HASH_TABLE_SIZE=4G
      - CACHEDEV=cachedev_1
    command: -a -c 1
